name: publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: "ubuntu-latest"
    environment:
      name: ci
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "3.11"
      - name: Install Python dependencies
        run: pip install --no-cache-dir build twine
      - name: Build package
        run: make build
      - name: Publish to PyPI
        run: make publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
